package com.akamai.testing.edgegrid.core;

import com.google.common.collect.ImmutableMultimap;
import com.google.common.collect.Multimap;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * HTTP Request agnostic to any HTTP client implementation.
 */
public class Request {

    private final String method;
    private final String uriWithQuery;
    private final Multimap<String, String> headers;
    private final String body;

    private Request(Builder b) {
        this.method = checkNotNull(b.method);
        this.uriWithQuery = checkNotNull(b.uriWithQuery);
        this.headers = b.headers;
        this.body = checkNotNull(b.body);
    }

    /**
     * Returns a new builder. The returned builder is equivalent to the builder
     * generated by {@link Builder}.
     */
    public static Builder builder() {
        return new Builder();
    }

    String getBody() {
        return body;
    }

    Multimap<String, String> getHeaders() {
        return headers;
    }

    String getMethod() {
        return method;
    }

    String getUriWithQuery() {
        return uriWithQuery;
    }

    @Override
    public String toString() {
        return "Request(method=" + method + ", uriWithQuery=" + uriWithQuery + ", body=" + body + ", headers=" + headers + ")";
    }

    /**
     * Creates a new builder. The returned builder is equivalent to the builder
     * generated by {@link Request#builder()}.
     */
    public static class Builder {

        private String method;
        private String uriWithQuery;
        private Multimap<String, String> headers = ImmutableMultimap.of();
        private String body = "";

        /**
         * Sets a content of HTTP request body. If not set, body is empty by default.
         */
        public Builder body(String requestBody) {
            this.body = requestBody;
            return this;
        }

        /**
         * Sets headers of HTTP request. If not set, headers list is empty by default
         */
        public Builder headers(Multimap<String, String> headers) {
            this.headers = ImmutableMultimap.copyOf(checkNotNull(headers));
            return this;
        }

        /**
         * Sets HTTP method: GET, PUT, POST, DELETE. Mandatory to set.
         */
        public Builder method(String method) {
            this.method = checkNotNull(method);
            return this;
        }

        /**
         * Sets absolute URI of HTTP request including query string. Mandatory to set.
         */
        public Builder uriWithQuery(String uriWithQuery) {
            this.uriWithQuery = checkNotNull(uriWithQuery);
            return this;
        }

        /**
         * Returns a newly-created immutable HTTP request.
         */
        public Request build() {
            return new Request(this);
        }

    }
}
